package grumpycat;

/**
 *
 * @author Jose Pablo Méndez Soto
 */
import javax.swing.ImageIcon;
import logic.GCExtractor;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class GrumpyCatFace extends javax.swing.JFrame {

    JFileChooser fileChooser;
    GCExtractor gpUnzipper;

    public GrumpyCatFace() {
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filePathTxtLbl = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnExtract = new javax.swing.JButton();
        lblUsage = new javax.swing.JLabel();
        pbExtraction = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHelp = new javax.swing.JMenu();
        itemHelpCont = new javax.swing.JMenuItem();
        itemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grumpycat File Extractor");
        setResizable(false);

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnExtract.setText("Extract Files");
        btnExtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtractActionPerformed(evt);
            }
        });

        lblUsage.setText("Provide a path to a folder or to a ZIP package:");

        menuHelp.setText("Help");

        itemHelpCont.setText("Help Contents");
        itemHelpCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHelpContActionPerformed(evt);
            }
        });
        menuHelp.add(itemHelpCont);

        itemAbout.setText("About");
        itemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(itemAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filePathTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExtract)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbExtraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblUsage))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUsage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filePathTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowse)
                    .addComponent(btnExtract)
                    .addComponent(pbExtraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsCustom() {
        fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        gpUnzipper = new GCExtractor();
        filePathTxtLbl.setText(fileChooser.getCurrentDirectory().toString());
        this.setLocationRelativeTo(null);
    }

    // buttons start here
    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        fileChooser.showOpenDialog(GrumpyCatFace.this);
        filePathTxtLbl.setText(fileChooser.getSelectedFile().toString());
        System.out.println("Selected file:" + fileChooser.getSelectedFile().toString());
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnExtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtractActionPerformed
        try {
            gpUnzipper.extractThemAll(fileChooser.getSelectedFile().toString());
        } catch(NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No file or folder selected yet."
                    + "\nPlease use the Browse button",
                    "Grumpycat Exception", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btnExtractActionPerformed

    private void itemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutActionPerformed
        String description = "Grumpycat\nA tool for TAC engineers."
                + "\nBy José Pablo Méndez Soto."
                + "\njmendez2@cisco.com"
                + "\nhttps://github.com/hurinth/grumpycat"
                + "\n2013";
        ImageIcon gcIcon = new ImageIcon(GrumpyCatFace.class.getResource("../media/gcp.jpg"));
        JOptionPane.showMessageDialog(this, description,
                "About this tool", JOptionPane.INFORMATION_MESSAGE, gcIcon);
    }//GEN-LAST:event_itemAboutActionPerformed

    private void itemHelpContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHelpContActionPerformed
        String help = "Browse through your computer's filesystem and point to a"
                + "\ndirectory where you already have several trace sets stored,"
                + "\nor choose a .zip file directly."
                + "\n\nGrumpycat **does not** extract the XML files that RTMT"
                + "\ngenerates, and deletes the compressed txt.gz archives "
                + "\nleaving only the useful traces that are pure text.";
        JOptionPane.showMessageDialog(this, help,
                "Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemHelpContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrumpyCatFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrumpyCatFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrumpyCatFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrumpyCatFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrumpyCatFace().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnExtract;
    private javax.swing.JTextField filePathTxtLbl;
    private javax.swing.JMenuItem itemAbout;
    private javax.swing.JMenuItem itemHelpCont;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUsage;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JProgressBar pbExtraction;
    // End of variables declaration//GEN-END:variables
}
